markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif

google_analytics_id: UA-33287620-2

repository: https://github.com/qdmounts

collections:
  docs:
    output: true
    title: docs
  products:
    output: true
    title: products

sale_active: false
sale_code: NRA2014
sale_ends: 2014-12-31
