markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif

DISABLED_gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-33287620-2

repository: https://github.com/prolixalias

collections:
  docs:
    output: true
    title: docs
  products:
    output: true
    title: products
