- title: QD Mounts
  products:
  - receiver-adapters
  - optic-adapters

- title: Fixed Mounts
  products:
  - picatinny-rails

- title: Rings
  products:
  - lever-rings
  - tactical-rings

- title: Muzzle Brakes
  products:
  - ar-brakes
  - standard-brakes
  - gunsmith-brakes

#- title: Industrial Mounts
#  products:
#  - github-pages
#  - deployment-methods

#- title: Miscellaneous
#  products:
#  - troubleshooting
